[package]
name = "caysdlib"
version = "0.1.0"
description = "Cavvy SDL2 绑定库"
authors = []
license = "MIT"
project_type = "lib"
main = "lib.cay"
src_dir = "src"
target_dir = "target"

[build]
opt_level = "2"
debug = false
static_link = true
cflags = []
ldflags = []
lib_paths = [
    "./Libs/SDL2/lib/x64",
]
lto = false
opt_ir = false
keep_ir = false

[lib]
only_include = true
exports = []
install_path = "lib"

[lib.header]
generate = true
include_prefix = ""

[ffi]
system_libs = []
include_paths = [
    "./Libs/SDL2/include",
]
link_options = []

[ffi.libraries.SDL2]
name = "SDL2"
lib = "SDL2"
path = "./Libs/SDL2/lib/x64"
static_lib = false
# deps = ["SDL2main"]

[ffi.libraries.SDL2.platform.windows]
lib = "SDL2"
path = "./Libs/SDL2/lib/x64"

[workspace]
lib_paths = [
    "./Libs/SDL2/lib/x64",
]

[dependencies]

[dev-dependencies]
